project:
  type: website
  output-dir: ../output

website:
  title: "darkwing"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - trips_analysis.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



