project:
  type: website
  output-dir: ../docs_output

website:
  title: "darkwing"
  site-url: https://ajfriend.github.io/darkwing/
  repo-url: https://github.com/ajfriend/darkwing
  repo-subdir: docs/
  repo-actions: [edit, issue]
  sidebar:
    style: "docked"
    search: true
    contents:
      - href: index.qmd
        text: Home
      - about.qmd
      - trips_analysis.qmd
      - duckdb_stuff.qmd

format:
  html:
    theme: cosmo
    css: styles.css
