project:
  type: website
  output-dir: ../docs_output

website:
  title: "duckboat"
  site-url: https://ajfriend.github.io/duckboat/
  repo-url: https://github.com/ajfriend/duckboat
  repo-subdir: docs/
  repo-actions: [edit, issue]
  sidebar:
    style: "docked"
    search: true
    contents:
      - href: index.qmd
        text: Home
      - concepts.qmd
      - duckdb_stuff.qmd
      - lazy.qmd
      - section: "Tutorials"
        contents:
          - href: tut_nyc_join.qmd
            text: NYC Trips Join
          - href: tut_lazy.ipynb
            text: Lazy Evaluation
          - href: tut_fsq.ipynb
            text: Foursquare POI
      - related.qmd
      - section: "Development"
        contents:
          - ramble.qmd
          - todo.qmd

  navbar:
    tools:
      - icon: github
        menu:
          - text: Source Code
            href:  https://github.com/ajfriend/duckboat
          - text: Issues
            href:  https://github.com/ajfriend/duckboat/issues
          - text: Discussions
            href:  https://github.com/ajfriend/duckboat/discussions


format:
  html:
    theme: cosmo
    css: styles.css
