name: wheels2

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build-and-inspect-package:
    name: Build & inspect package.
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: hynek/build-and-inspect-python-package@v2
